/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import org.apache.commons.lang3.RandomStringUtils;
import Control.ClientCtr;
import Model.GameMatch;
import Model.Group;
import Model.GroupMember;
import Model.MatchRequest;
import Model.ObjectWrapper;
import Model.Player;
import Model.PlayerStat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demo
 */
public class PlayerMainFrm extends javax.swing.JFrame {

    private static Player player;
    private PlayerStat playerStat;
    private static ClientCtr myctrl;
    private LinkedHashMap<Integer, Integer> playerOnline;
    private Player chosenPlayer;
    private ArrayList<Group> listGroup;
    private List<GroupMember> listMember;
    private int countMatchRequest;
    private GroupMember member;
    private int rank, first = 1;
    private LinkedHashMap<Player, PlayerStat> scoreboard;
    private LinkedHashMap<Player, Integer> scoreboard_Rank;
    private HashMap<Player, String> friendRequest;
    private String roomID = "";
    private List<Player> participant;
    private List<MatchRequest> listMatchRequest;

    /**
     * Creates new form PlayerMainFrm
     */
    public PlayerMainFrm(Player player, ClientCtr ctrl) {
        super(player.getName());
        this.player = player;
        myctrl = ctrl;
        init();
        initComponents();
        invite.setVisible(false);
        cancleFriend.setVisible(false);
        groupMatch.setVisible(false);
        btnAcceptFriendRequest.setVisible(false);
        btnRejectFriendRequest.setVisible(false);
        txtRoomID.setVisible(false);
        btnStart.setVisible(false);
        jLabel7.setText("You have 0 invitation(s)");
        jLabel23.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cancleFriend = new javax.swing.JButton();
        invite = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        friendOff = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        friendList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGroup = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        groupMatch = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        globalScore = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblFriendRequest = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        btnAcceptFriendRequest = new javax.swing.JButton();
        btnRejectFriendRequest = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatchRequest = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCreateRoom = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblParticipant = new javax.swing.JTable();
        btnStart = new javax.swing.JButton();
        txtRoomID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel3.setText("List friend online: ");

        jLabel4.setText("List friend offline:");

        jLabel8.setText("Statistic");

        jLabel9.setText("Total Match played:");

        jLabel10.setText("Win rate");

        jLabel11.setText("The role played most: ");

        jLabel12.setText(String.valueOf(playerStat.getTotalGameMatch()));

        jLabel13.setText(String.valueOf(playerStat.getWinrate()));

        jLabel14.setText(playerStat.getMostUseRole());

        jLabel15.setText("Player:");

        jLabel16.setText(chosenPlayer.getName());

        cancleFriend.setText("Cancle Friendship");
        cancleFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleFriendActionPerformed(evt);
            }
        });

        invite.setText("Invite to play game");
        invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteActionPerformed(evt);
            }
        });

        jButton2.setText(player.getName());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Rank:");

        jLabel21.setText("Loading ... ");

        friendOff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        friendOff.setFixedCellHeight(50);
        friendOff.setFixedCellWidth(50);
        friendOff.setName(""); // NOI18N
        friendOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendOffMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(friendOff);

        friendList.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        friendList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        friendList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        friendList.setFixedCellHeight(50);
        friendList.setFixedCellWidth(50);
        friendList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendListMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(friendList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel21)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(invite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addComponent(cancleFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(invite)
                                    .addComponent(cancleFriend))
                                .addContainerGap(92, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jTabbedPane2.addTab("Info", jPanel1);

        jButton4.setText("Join new group");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Group ");

        jButton3.setText("Leave group");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setText("All the group you have joined");

        tblGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGroupMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGroup);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("All member:");

        groupMatch.setText("Play Group Match");
        groupMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMatchActionPerformed(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblMember);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel18)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(groupMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(36, 36, 36)
                        .addComponent(groupMatch))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Group", jPanel3);

        jLabel5.setText("Your rank:");

        globalScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        globalScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                globalScoreMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(globalScore);

        jLabel17.setText("Loading ...");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addGap(138, 138, 138)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton5)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Global Scoreboard", jPanel2);

        tblFriendRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFriendRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFriendRequestMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblFriendRequest);

        jLabel22.setText("");

        btnAcceptFriendRequest.setText("Accept");
        btnAcceptFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptFriendRequestActionPerformed(evt);
            }
        });

        btnRejectFriendRequest.setText("Reject");
        btnRejectFriendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectFriendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel22)
                        .addGap(562, 562, 562)
                        .addComponent(btnAcceptFriendRequest)
                        .addGap(79, 79, 79)
                        .addComponent(btnRejectFriendRequest))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAcceptFriendRequest)
                            .addComponent(btnRejectFriendRequest))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(135, 135, 135))))
        );

        jTabbedPane2.addTab("Friend Request", jPanel4);

        tblMatchRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMatchRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatchRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatchRequest);

        jLabel7.setText("You have some invitaion: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Match request", jPanel5);

        btnCreateRoom.setText("Create a room to play!");
        btnCreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoomActionPerformed(evt);
            }
        });

        tblParticipant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane8.setViewportView(tblParticipant);

        btnStart.setText("Start to play");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtRoomID.setText("jTextField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreateRoom)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Play game now!", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addGap(409, 409, 409))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // button to show the main player
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chosenPlayer = player;
        invite.setVisible(false);
        cancleFriend.setVisible(false);
        findRank(chosenPlayer.getId());

        jLabel21.setText(String.valueOf(rank));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.STATISTIC, player.getId()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteActionPerformed
        // TODO add your handling code here
        if (chosenPlayer.getStatus().equals("FREE")) {
            String roomId = JOptionPane.showInputDialog("Send room ID to this player");
            sendMatchRequest(roomId);

        } else {
            JOptionPane.showMessageDialog(this, "This player cannot play right now! Maybe next time!");
        }
    }//GEN-LAST:event_inviteActionPerformed

    // show the info of the friend that is offline
    private void friendOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendOffMouseClicked
        // TODO add your handling code here:
        for (Player pl : player.getFriend()) {
            if (pl.getName().equals(friendOff.getSelectedValue())) {
                chosenPlayer = pl;
                break;
            }
        }
        invite.setVisible(false);
        cancleFriend.setVisible(true);
        findRank(chosenPlayer.getId());

        jLabel21.setText(String.valueOf(rank));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.STATISTIC, chosenPlayer.getId()));
    }//GEN-LAST:event_friendOffMouseClicked

    // show the info of the friend player
    private void friendListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendListMouseClicked
        // TODO add your handling code here:
        for (Player pl : player.getFriend()) {
            if (pl.getName().equals(friendList.getSelectedValue())) {
                chosenPlayer = pl;
                break;
            }
        }
        invite.setVisible(true);
        cancleFriend.setVisible(true);
        findRank(chosenPlayer.getId());

        jLabel21.setText(String.valueOf(rank));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.STATISTIC, chosenPlayer.getId()));

    }//GEN-LAST:event_friendListMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    // cancle membership
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = tblGroup.getSelectedRow();
        for (GroupMember gm : listGroup.get(row).getMember()) {
            if (gm.getPlayer().getId() == player.getId()) {
                myctrl.sendData(new ObjectWrapper(ObjectWrapper.CANCLE_MEMBER, gm));
                break;
            }
        }
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_GROUP_JOINED, player.getId()));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGroupMouseClicked
        // TODO add your handling code here:
        groupMatch.setVisible(true);
        int column = tblGroup.getColumnModel().getColumnIndexAtX(evt.getX()); // get the coloum of the button
        int row = evt.getY() / tblGroup.getRowHeight(); // get the row of the button
        int groupId = listGroup.get(row).getId();
        // *Checking the row or column is valid or not
        if (row < tblGroup.getRowCount() && row >= 0 && column < tblGroup.getColumnCount() && column >= 0) {
            listMember = (List) listGroup.get(row).getMember();
            String[] columnNames = {"Id", "Name", "Online/Offline"};
            String[][] value = new String[listMember.size()][columnNames.length];
            for (int i = 0; i < listMember.size(); i++) {
                value[i][0] = listMember.get(i).getPlayer().getId() + "";
                value[i][1] = listMember.get(i).getPlayer().getName();
//                if(Integer.parseInt(value[i][0]) == player.getId()){
//                    member = listMember.get(i);
//                }
                if (playerOnline.containsKey(listMember.get(i).getPlayer().getId())) {
                    value[i][2] = "Online";
                } else {
                    value[i][2] = "Offline";
                }
            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            tblMember.setModel(tableModel);
        }
    }//GEN-LAST:event_tblGroupMouseClicked

    private void groupMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupMatchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_groupMatchActionPerformed

    private void tblFriendRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFriendRequestMouseClicked
        // TODO add your handling code here:
        int row = tblFriendRequest.getSelectedRow();
        jLabel22.setText("Information about: " + (String) tblFriendRequest.getValueAt(row, 2));
        btnAcceptFriendRequest.setVisible(true);
        btnRejectFriendRequest.setVisible(true);

    }//GEN-LAST:event_tblFriendRequestMouseClicked

    private void btnAcceptFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptFriendRequestActionPerformed
        // TODO add your handling code here:
        int row = tblFriendRequest.getSelectedRow();
        Player fr = new Player();
        fr.setId(Integer.parseInt((String) tblFriendRequest.getValueAt(row, 1)));
        ArrayList<Player> arrPlayers = new ArrayList<>();
        arrPlayers.add(player);
        arrPlayers.add(fr);
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.ACCEPT_FRIEND_REQUEST, arrPlayers));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.FRIEND_LIST, player.getId()));
    }//GEN-LAST:event_btnAcceptFriendRequestActionPerformed

    private void btnRejectFriendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectFriendRequestActionPerformed
        // TODO add your handling code here:
        int row = tblFriendRequest.getSelectedRow();
        Player fr = new Player();
        fr.setId(Integer.parseInt((String) tblFriendRequest.getValueAt(row, 1)));
        ArrayList<Player> arrPlayers = new ArrayList<>();
        arrPlayers.add(player);
        arrPlayers.add(fr);
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.REJECT_FRIEND_REQUEST, arrPlayers));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.FRIEND_LIST, player.getId()));
    }//GEN-LAST:event_btnRejectFriendRequestActionPerformed

    private void globalScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_globalScoreMouseClicked
        // TODO add your handling code here:
        int row = globalScore.getSelectedRow();
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_PLAYER_ID, Integer.parseInt((String) ((DefaultTableModel) globalScore.getModel()).getValueAt(row, 1))));
        String status = (String) ((DefaultTableModel) globalScore.getModel()).getValueAt(row, 5);

        if (!check(Integer.parseInt((String) ((DefaultTableModel) globalScore.getModel()).getValueAt(row, 1)))) {
            String[] options = {"Send Friend request", "Invite to play game", "Cancle"};
            int x = JOptionPane.showOptionDialog(this, "You guys are not friend! Do you want to make friend with this player?",
                    "Choose action: ", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            System.out.println(status);
            System.out.println(chosenPlayer.getId() + " " + chosenPlayer.getStatus());
            if (x == 0) {
                ArrayList<Player> arr = new ArrayList<>();
                arr.add(player);
                arr.add(chosenPlayer);
                myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEND_FRIEND_REQUEST, arr));

            } else if (x == 1) {
                if (status.equals("Online") && chosenPlayer.getStatus().equals("FREE")) {
                    String roomId = JOptionPane.showInputDialog("Send room ID to this player");
                    sendMatchRequest(roomId);
                } else {
                    JOptionPane.showMessageDialog(this, "This player cannot play right now! Maybe next time!");
                }
            }
        } else {
            String[] options = {"Invite to play game", "Cancle"};
            int x = JOptionPane.showOptionDialog(this, "You guys are friend! Do you want to invite this player to play a game ?",
                    "Choose action: ", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            //System.out.println(chosenPlayer.getStatus());
            if (x == 0 && status.equals("Online") && chosenPlayer.getStatus().equals("FREE")) {
                String roomId = JOptionPane.showInputDialog("Send room ID to this player");
                sendMatchRequest(roomId);

            } else {
                JOptionPane.showMessageDialog(this, "This player cannot play right now! Maybe next time!");
            }
        }
    }//GEN-LAST:event_globalScoreMouseClicked

    private void cancleFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleFriendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancleFriendActionPerformed

    private void btnCreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoomActionPerformed
        // TODO add your handling code here:
        btnCreateRoom.setVisible(false);

        btnStart.setVisible(true);

        roomID = RandomStringUtils.randomAlphanumeric(5).toUpperCase();
        txtRoomID.setVisible(true);
        txtRoomID.setEditable(false);
        txtRoomID.setText("Room ID: " + roomID);
        GameMatch gameMatch = new GameMatch();
        gameMatch.setDescription(roomID);
        gameMatch.setType("Random");
        participant = new ArrayList<>();
        participant.add(player);
        tblParticipant.setVisible(true);
        String[] columnNames = {"Id", "Name"};
        String[][] value = new String[participant.size()][2];
        for (int i = 0; i < participant.size(); i++) {
            value[i][0] = participant.get(i).getId() + "";
            value[i][1] = participant.get(i).getName();
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        tblParticipant.setModel(tableModel);
        ArrayList<Object> game = new ArrayList<>();
        game.add((Object) gameMatch);
        game.add((Object) player);
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.CREATE_A_ROOM, game));
    }//GEN-LAST:event_btnCreateRoomActionPerformed

    private void tblMatchRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatchRequestMouseClicked
        // TODO add your handling code here:
        int row = tblMatchRequest.getSelectedRow();
        String match_roomID = (String) ((DefaultTableModel) tblMatchRequest.getModel()).getValueAt(row, 2);
        String[] options = {"Accept", "Reject", "Cancle"};
        int x = JOptionPane.showOptionDialog(this, "Do you accept the invitation?",
                "Reply invitation: ", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
        if (x == 0) {
            ((DefaultTableModel) tblMatchRequest.getModel()).removeRow(tblMatchRequest.getSelectedRow());
            if (!roomID.isBlank()) {
                ArrayList<Object> arr = new ArrayList<>();
                arr.add(roomID);
                arr.add(player);
                myctrl.sendData(new ObjectWrapper(ObjectWrapper.QUIT_OLD_ROOM, arr));
            }
            roomID = match_roomID;
            System.out.println("row is " + row);
            myctrl.sendData(new ObjectWrapper(ObjectWrapper.ACCEPT_MATCH_REQUEST, listMatchRequest.get(row)));
            listMatchRequest.remove(row);
        } else if (x == 1) {
            ((DefaultTableModel) tblMatchRequest.getModel()).removeRow(tblMatchRequest.getSelectedRow());
            myctrl.sendData(new ObjectWrapper(ObjectWrapper.REJECT_MATCH_REQUEST, listMatchRequest.get(row)));
            listMatchRequest.remove(row);
        }
//        myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_RO, Integer.parseInt((String) ((DefaultTableModel) tblMatchRequest.getModel()).getValueAt(row, 2))));
//        String status = (String) ((DefaultTableModel) globalScore.getModel()).getValueAt(row, 5);

    }//GEN-LAST:event_tblMatchRequestMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.START_GAME, roomID));
    }//GEN-LAST:event_btnStartActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (!txtSearch.getText().isBlank()) {
            String key = txtSearch.getText().trim();
            myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_PLAYER_NAME, key));
        } else {
            updateScoreboard();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerMainFrm(player, myctrl).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptFriendRequest;
    private javax.swing.JButton btnCreateRoom;
    private javax.swing.JButton btnRejectFriendRequest;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cancleFriend;
    private java.awt.Canvas canvas1;
    private javax.swing.JList<String> friendList;
    private javax.swing.JList<String> friendOff;
    private javax.swing.JTable globalScore;
    private javax.swing.JButton groupMatch;
    private javax.swing.JButton invite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblFriendRequest;
    private javax.swing.JTable tblGroup;
    private javax.swing.JTable tblMatchRequest;
    private javax.swing.JTable tblMember;
    private javax.swing.JTable tblParticipant;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // update the friend list
    public void receivedDataProcessingFriendlist(ObjectWrapper data) {
        if (data.getData() instanceof ArrayList<?>) {
            player.setFriend((ArrayList<Player>) data.getData());
            updateFriendList();
        }
    }

    public void receivedDataProcessingSearchPlayer(ObjectWrapper data) {
        if (data.getData() instanceof Player) {
            chosenPlayer = (Player) data.getData();
            System.out.println("chosen player is " + chosenPlayer.getName() + " " + chosenPlayer.getId());
        }
    }

    // update the online status
    public void receivedDataProcessingOnline(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

        if (data.getData() instanceof LinkedHashMap<?, ?>) {
            playerOnline = (LinkedHashMap<Integer, Integer>) data.getData();
            System.out.println("update online " + playerOnline.size());
            if (first != 1) {
                first = 0;
                updateFriendList();
                updateGroupMember();
                updateScoreboard();
            }
            first = 0;
        }
    }

    // update the Statistic 
    public void receivedDataProcessingStat(ObjectWrapper data) {
        if (data.getData() instanceof PlayerStat) {
            playerStat = (PlayerStat) data.getData();
            jLabel12.setText(String.valueOf(playerStat.getTotalGameMatch()));
            jLabel13.setText(String.valueOf(playerStat.getWinrate()));
            jLabel14.setText(String.valueOf(playerStat.getMostUseRole()));
            jLabel16.setText(String.valueOf(chosenPlayer.getName()));
        }
    }

    // show the group player joined
    public void receivedDataProcessingGroup(ObjectWrapper data) {
        if (data.getData() instanceof ArrayList<?>) {
            listGroup = (ArrayList<Group>) data.getData();

            String[] columnNames = {"Id", "Name", "founder"};
            String[][] value = new String[listGroup.size()][columnNames.length];
            for (int i = 0; i < listGroup.size(); i++) {
                value[i][0] = listGroup.get(i).getId() + "";
                value[i][1] = listGroup.get(i).getName();
                value[i][2] = listGroup.get(i).getFounderName();

            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            tblGroup.setModel(tableModel);
        } else {
            tblGroup.setModel(null);
        }
    }

    // show the group member
    public void receivedDataProcessingMember(ObjectWrapper data) {
        if (data.getData() instanceof ArrayList<?>) {
            listMember = (ArrayList<GroupMember>) data.getData();
            updateGroupMember();
        }
    }

    // update the scoreboard
    public void receivedDataProcessingScoreboard(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof LinkedHashMap<?, ?>) {
            scoreboard = (LinkedHashMap<Player, PlayerStat>) data.getData();
            //System.out.println(scoreboard.size());
            updateScoreboard();
        }
    }

    // load all the friend requests are pending
    public void receivedDataProcessingFriendRequestPending(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof HashMap<?, ?>) {
            friendRequest = (HashMap<Player, String>) data.getData();
            String[] columnNames = {"Rank", "ID", "Name", "Time send", "Online/Offline"};
            String[][] value = new String[friendRequest.size()][columnNames.length];
            int i = 0;
            for (Map.Entry<Player, String> e : friendRequest.entrySet()) {
                Player ep = e.getKey();
                findRank(ep.getId());
                value[i][0] = String.valueOf(rank);
                value[i][1] = String.valueOf(ep.getId());
                value[i][2] = ep.getName();
                value[i][3] = e.getValue();

                if (playerOnline.containsKey(ep.getId())) {
                    value[i][4] = "Online";
                } else {
                    value[i][4] = "Offline";
                }

                ++i;
            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            tblFriendRequest.setModel(tableModel);
        } else {
            tblFriendRequest.setModel(null);

        }
    }

    public void receivedDataProcessingAnsFriendRequest(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof String) {
            String res = (String) data.getData();
            if (res.equals("false")) {
                JOptionPane.showMessageDialog(this, "Something wrong happened! Please try again");

            } else {
                JOptionPane.showMessageDialog(this, "You have successfully " + res + " this friend request!");
                ((DefaultTableModel) tblFriendRequest.getModel()).removeRow(tblFriendRequest.getSelectedRow());
            }
            btnAcceptFriendRequest.setVisible(false);
            btnRejectFriendRequest.setVisible(false);
        }
    }

    public void receivedDataProcessingSendFriendRequest(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof String) {
            String res = (String) data.getData();
            if (res.equals("false")) {
                JOptionPane.showMessageDialog(this, "Something wrong happened! Please try again");

            } else {
                JOptionPane.showMessageDialog(this, "You have successfully send friend request !");
            }

        }
    }

    public void receivedDataProcessingMatchRequest(ObjectWrapper data) {
        if (data.getData() instanceof MatchRequest) {
            MatchRequest mtchreq = (MatchRequest) data.getData();
            listMatchRequest.add(mtchreq);
            System.out.println(listMatchRequest.size());
            String[] columnNames = {"From ID", "Name", "Room ID"};
            String[][] value = new String[listMatchRequest.size()][columnNames.length];
            int i = 0;
            for (MatchRequest mr : listMatchRequest) {
                if (mr.getReceiver().getName().equals(player.getName())) {
                    value[i][0] = String.valueOf(mr.getSender().getId());
                    value[i][1] = mr.getSender().getName();
                    value[i][2] = mr.getRoomID();
                    ++i;
                }
            }
            jLabel7.setText("You have " + i + " invitation(s)");

            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            tblMatchRequest.setModel(tableModel);
        }
    }

    public void receivedDataProcessingStatusMatchRequest(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof String) {
            if (((String) data.getData()).equals("exist")) {
                JOptionPane.showMessageDialog(this, "You've send this request before!Wait for the reply!");
            } else {
                JOptionPane.showMessageDialog(this, "This player will get the request soon!");
            }
        }
    }

    private void sendMatchRequest(String roomId) {
        if (!roomId.isEmpty()) {
            MatchRequest mr = new MatchRequest(player, chosenPlayer, roomId);
            myctrl.sendData(new ObjectWrapper(ObjectWrapper.INVITE_MATCH, mr));
        }
    }

    public void receivedDataProcessingUpdateRoomPlay(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof List<?>) {
            participant = (List<Player>) data.getData();
            updateParticipantTable();
        }
    }

    public void receivedDataProcessingReceiveSignal(ObjectWrapper data) {
        if (data.getData() instanceof Integer) {
            int signal = (Integer) data.getData();
            switch (signal) {
                case 1:
                    myctrl.sendData(new ObjectWrapper(ObjectWrapper.LOAD_FRIEND_REQUEST, player));
                    break;
                case 2:
                    myctrl.sendData(new ObjectWrapper(ObjectWrapper.FRIEND_LIST, player.getId()));
                    break;
            }
        }
    }

    public void receivedDataProcessingRemoveMatchRequest(ObjectWrapper data) {
        if (data.getData() instanceof Player) {
            Player sender = (Player) data.getData();
            for (MatchRequest mr : listMatchRequest) {
                if (mr.getSender().getId() == sender.getId()) {
                    listMatchRequest.remove(mr);
                    break;
                }
            }
            updateMatchRequest();
        }
    }

    private void updateMatchRequest() {
        String[] columnNames = {"From ID", "Name", "Room ID"};
        String[][] value = new String[listMatchRequest.size()][columnNames.length];
        int i = 0;
        for (MatchRequest mr : listMatchRequest) {
            if (mr.getReceiver().getName().equals(player.getName())) {
                value[i][0] = String.valueOf(mr.getSender().getId());
                value[i][1] = mr.getSender().getName();
                value[i][2] = mr.getRoomID();
                ++i;
            }
        }
        jLabel7.setText("You have " + i + " invitation(s)");

        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        tblMatchRequest.setModel(tableModel);
    }

    private void updateFriendList() {
        int i = 0, j = 0;
        String frlist[] = new String[player.getFriend().size()];
        String froff[] = new String[player.getFriend().size()];
        for (Player fr : player.getFriend()) {
            if (playerOnline.containsKey(new Integer(fr.getId()))) {
                frlist[i++] = fr.getName();

            } else {
                froff[j++] = fr.getName();
            }
        }
        //System.out.println(frlist[0]+frlist[1]);
        friendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = frlist.clone();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }

        });
        friendOff.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = froff.clone();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void updateGroupMember() {
        if (listMember.size() != 0) {
            String[] columnNames = {"Id", "Name", "Online/Offline"};
            String[][] value = new String[listMember.size()][columnNames.length];
            for (int i = 0; i < listMember.size(); i++) {
                value[i][0] = listMember.get(i).getPlayer().getId() + "";
                value[i][1] = listMember.get(i).getPlayer().getName();
                if (playerOnline.containsKey(listMember.get(i).getPlayer().getId())) {
                    value[i][2] = "Online";
                } else {
                    value[i][2] = "Offline";
                }

            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            tblMember.setModel(tableModel);
        }
    }

    private void findRank(int playerID) {
        int i = 1;
        for (Map.Entry<Player, PlayerStat> e : scoreboard.entrySet()) {
            if (playerID == e.getKey().getId()) {
                rank = i;
                break;
            }
            ++i;
        }
    }

    private void updateScoreboard() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String[] columnNames = {"Rank", "ID", "Name", "Total Match", "Win rate", "Online/Offline"};
        String[][] value = new String[scoreboard.size()][columnNames.length];
        int i = 0, k = 1;
        for (Map.Entry<Player, PlayerStat> e : scoreboard.entrySet()) {
            Player ep = e.getKey();
            PlayerStat eps = e.getValue();
            scoreboard_Rank.put(ep, k);
            value[i][0] = String.valueOf(k);
            value[i][1] = String.valueOf(ep.getId());
            value[i][2] = ep.getName();
            value[i][3] = String.valueOf(eps.getTotalGameMatch());
            value[i][4] = String.valueOf(eps.getWinrate());
            if (playerOnline.containsKey(ep.getId())) {
                value[i][5] = "Online";
            } else {
                value[i][5] = "Offline";
            }
            if (player.getId() == ep.getId()) {
                rank = k;
                jLabel17.setText(String.valueOf(rank));
                jLabel21.setText(String.valueOf(rank));
            }
            ++i;
            ++k;
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        globalScore.setModel(tableModel);

    }

    private boolean check(int id) {
        for (Player pl : player.getFriend()) {
            if (id == pl.getId()) {
                return true;
            }
        }
        return false;
    }

    private void updateParticipantTable() {
        btnCreateRoom.setVisible(false);
        if (player.getId() == participant.get(0).getId()) {
            btnStart.setVisible(true);
        } else {
            btnStart.setVisible(false);
        }
        txtRoomID.setVisible(true);
        txtRoomID.setEditable(false);
        txtRoomID.setText("Room ID: " + roomID);
        String[] columnNames = {"Id", "Name"};
        String[][] value = new String[participant.size()][2];
        for (int i = 0; i < participant.size(); i++) {
            if (playerOnline.containsKey(participant.get(i).getId())) {
                value[i][0] = participant.get(i).getId() + "";
                value[i][1] = participant.get(i).getName();
            }

        }
        jLabel23.setVisible(true);
        jLabel23.setText(" " + "/" + participant.size());
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        tblParticipant.setModel(tableModel);
    }
    
    private Player checkPlayer(Player player){
        for(Player pl : scoreboard.keySet()){
            if(pl.getId() == player.getId()){
                return pl;
            }
        }
        return player;
    }
    private void init() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        playerOnline = new LinkedHashMap<>();
        chosenPlayer = new Player();
        chosenPlayer.setName(player.getName());
        chosenPlayer.setId(player.getId());
        playerStat = new PlayerStat();
        friendRequest = new HashMap<>();
        listMatchRequest = new ArrayList<>();
        participant = new ArrayList<>();
        scoreboard_Rank = new LinkedHashMap<>();
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_FRIEND_LIST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.PLAYER_ONLINE, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_STATISTIC, this));
        listGroup = new ArrayList<>();
        listMember = new ArrayList<>();
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_GROUP_JOINED, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_GROUP, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_MEMBER, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.GLOBAL_SCOREBOARD, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_LOAD_FRIEND_REQUEST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_ANS_FRIEND_REQUEST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEND_FRIEND_REQUEST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_PLAYER_ID, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.INVITE_MATCH, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_INVITE_MATCH, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.UPDATE_FRIEND_LIST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.UPDATE_ROOM_PLAY, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_START_GAME, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.RECEIVE_SIGNAL, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REMOVE_MATCH_REQUEST, this));
        myctrl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_PLAYER_NAME, this));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.FRIEND_LIST, player.getId()));
        //myctrl.sendData(new ObjectWrapper(ObjectWrapper.PLAYER_ONLINE, null));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.STATISTIC, chosenPlayer.getId()));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.GLOBAL_SCOREBOARD, null));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_GROUP_JOINED, player.getId()));
        myctrl.sendData(new ObjectWrapper(ObjectWrapper.LOAD_FRIEND_REQUEST, player));

    }

    public void receivedDataProcessingStartGame(ObjectWrapper data) {

    }

    public void receivedDataProcessingSearchPlayerByName(ObjectWrapper data) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (data.getData() instanceof List) {
            List<Player> listSearchPlayers = (List) data.getData();
            System.out.println(listSearchPlayers.size());
            if(listSearchPlayers.isEmpty()) return;
            String[] columnNames = {"Rank", "ID", "Name", "Total Match", "Win rate", "Online/Offline"};
            String[][] value = new String[scoreboard.size()][columnNames.length];
            int i = 0;
            
            for (Player pe :listSearchPlayers) { 
                Player e = checkPlayer(pe);
                boolean ok = scoreboard.containsKey(e);
                if(!ok) continue;
                value[i][0] = String.valueOf(scoreboard_Rank.get(e));
                value[i][1] = String.valueOf(e.getId());
                value[i][2] = e.getName();
                value[i][3] = String.valueOf(scoreboard.get(e).getTotalGameMatch());
                value[i][4] = String.valueOf(scoreboard.get(e).getWinrate());
                if (playerOnline.containsKey(e.getId())) {
                    value[i][5] = "Online";
                } else {
                    value[i][5] = "Offline";
                }
                ++i;
            }
            DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //unable to edit cells
                    return false;
                }
            };
            globalScore.setModel(tableModel);

        }
    }

}
